download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/hifis-toolkit-5.3.0.tar.gz
format_version: 1.0.0
name: toolkit
namespace: hifis
server: https://galaxy.ansible.com/api/
signatures: []
version: 5.3.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/hifis/toolkit/versions/5.3.0/
