---
roles:

- name: gothick.awscli
  src: https://github.com/gothick/ansible-awscli.git

#  - name: boutetnico.awscli
#    version: 5.0.0

#  - name: Oefenweb.postfix
#    version: v3.6.4

# - name: geerlingguy.pip
#   version: 3.0.3

