---
roles:

  - name: gothick.awscli
    src: https://github.com/gothick/ansible-awscli.git

  - name: gothick.ghostty
    src: https://github.com/gothick/ansible-ghostty.git

  - name: arillso.sudoers
    version: 2.3.0

  - name: Oefenweb.postfix
    version: v3.6.4

  - name: geerlingguy.apache
    version: 4.0.0

  - name: geerlingguy.php
    version: 6.0.0

  - name: geerlingguy.certbot
    version: 5.2.0

  - name: Oefenweb.nodejs
    version: v8.0.0

  - name: Oefenweb.yarn
    version: v1.0.56

  - name: geerlingguy.java
    version: 2.5.0

  - name: geerlingguy.elasticsearch
    version: 5.1.2

  - name: geerlingguy.mysql
    version: 4.3.4

collections:
  - name: basicbind.swap_file
    version: 2.0.3
