---
dev_site_path: /var/www/sites/dev
well_known_dir: /var/www/well-known/dev
dev_server_name: dev.gothick.org.uk
php_apache_server_root: /etc/apache2
dev_conf_name: "dev.conf"
dev_conf_ssl_name: "dev-ssl.conf"
dev_key_path: /etc/ssl/private/ssl-cert-dev.key
dev_cert_path: /etc/ssl/certs/ssl-cert-dev.pem