---
- name: Install and configure PHP-FPM
  hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Install various PHP dependencies
      ansible.builtin.apt:
        state: present
        update_cache: true
        cache_valid_time: 3600
        name:
          - composer
          # TODO: Why are we installing ACL? Our filesystems don't have ACL support...
          - acl
          - imagemagick
          - aspell

  roles:
    - geerlingguy.php
