# For basicbind.swap_file.swap_file role

# Full path to swap file
swap_file_path: '/var/swap'

# "present" creates the swap file, "absent" removes it
swap_file_state: 'present'

# Size in human readable form as is understood by filter "human_to_bytes"
# eg: 1G, 1M. Defaults to G
swap_file_size: '2G'

# Priority for the swap file. "Higher values indicate higher priority".
swap_file_priority: -1

# Choose between using "fallocate" and "dd" to create the swap file.
swap_file_create_cmd: '{{ omit }}'
