---
# Root folder containing our configured webdav folders
webdav_dir: /var/www/webdav

# docroot for well-known dir for acme challenges
well_known_docroot: "{{ acme_well_known_dir }}/webdav"

webdav_conf_dir: '/etc/webdav'
webdav_digest_file: "{{ webdav_conf_dir }}/htdigest"

webdav_server_name: "webdav.gothick.org.uk{{ test_hostname_suffix | default('') }}"

certs:
  - domains: "[ {{ webdav_server_name }} ]"
    email: "{{ acme_email }}"
    webroot: "{{ well_known_docroot }}"
