download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/basicbind-swap_file-2.0.3.tar.gz
format_version: 1.0.0
name: swap_file
namespace: basicbind
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.3
version_url: /api/v3/plugin/ansible/content/published/collections/index/basicbind/swap_file/versions/2.0.3/
