---
- name: Install S3 restore scripts
  hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:

    - name: Create recovery directory
      ansible.builtin.file:
        path: "{{ recovery_dir }}"
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Install grab backups script
      ansible.builtin.template:
        src: grab_latest_backups_from_s3.sh.j2
        dest: /usr/local/bin/grab_latest_backups_from_s3.sh
        owner: root
        group: root
        mode: "0744"

    - name: Install files restore scripts
      ansible.builtin.template:
        src: restore_files_backup.sh.j2
        dest: "{{ item.destination }}"
        owner: root
        group: root
        mode: '0744'
      loop: "{{ files_scripts }}"

    - name: Install DB restore script
      ansible.builtin.template:
        src: restore_mysql_backup.sh.j2
        dest: /usr/local/bin/restore_mysql_backup.sh
        owner: root
        group: root
        mode: '0744'
