---
recovery_dir: "/data/recovery"

files_scripts:
  - destination: /usr/local/bin/restore_www_backup.sh
    recovery_dir: "{{ recovery_dir }}"
    tarball: www.tgz
    target_dir: var/www

  - destination: /usr/local/bin/restore_docker_backup.sh
    recovery_dir: "{{ recovery_dir }}"
    tarball: docker.tgz
    target_dir: var/docker

  - destination: /usr/local/bin/restore_mysql_files_backup.sh
    recovery_dir: "{{ recovery_dir }}"
    tarball: mysql-files.tgz
    target_dir: var/lib/mysql

  - destination: /usr/local/bin/restore_home_backup.sh
    recovery_dir: "{{ recovery_dir }}"
    tarball: home.tgz
    target_dir: home
