---
- name: Install awscli. This installs v1 on jammy, v2 on noble. Fine by me.
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - awscli

- name: Get specified user's home directory
  ansible.builtin.user:
    name: "{{ awscli_config_user }}"
    state: present
  register: user_info
  check_mode: true # Don't create the user if they don't exist

- name: Fail if no user found
  ansible.builtin.fail:
    msg: "User doesn't exist. Create user {{ awscli_config_user }} before using this playbook."
  when: user_info.changed

- name: Set config dir
  ansible.builtin.set_fact:
    awscli_config_dir: "{{ user_info.home }}/.aws"

- name: Create config file directory
  ansible.builtin.file:
    path: "{{ awscli_config_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ awscli_config_user }}"
    group: "{{ awscli_config_user }}"
  when: awscli_config_ids|length > 0

- name: Create config file
  ansible.builtin.template:
    src: config.j2
    dest: "{{ awscli_config_dir }}/config"
    owner: "{{ awscli_config_user }}"
    group: "{{ awscli_config_user }}"
    mode: '0600'

- name: Create credentials file
  ansible.builtin.template:
    src: credentials.j2
    dest: "{{ awscli_config_dir }}/credentials"
    owner: "{{ awscli_config_user }}"
    group: "{{ awscli_config_user }}"
    mode: '0600'
