---
- name: Install basic tools
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - emacs-nox
      - unzip
      - ncdu
      - iotop
      - git
