---
- name: Install tools we find generally useful, e.g. emacs, unzip
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - emacs-nox
      - unzip
      - ncdu
      - iotop
      - git
