# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Converge"
  hosts: "all"
  vars:
    netplan_ethernets:
      - interface_name: "eth0"
        dhcp4: "no"
        routes:
          - to: "default"
            via: "10.123.0.1"
          - to: "172.16.0.0/24"
            via: "10.123.0.100"
        addresses:
          - "10.123.0.10/24"
        nameservers:
          addresses:
            - "8.8.8.8"
            - "9.9.9.9"
          search:
            - "domain.local"
            - "domain.name"
  tasks:
    - name: "Include netplan_role"
      ansible.builtin.include_role:
        name: "hifis.toolkit.netplan"

...
