# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

collections:
  - name: "ansible.posix"
  - name: "community.crypto"
  - name: "community.general"

roles:
  - name: "geerlingguy.docker"
