---
web_users_zsh_theme: fishy
web_users_default_shell: /bin/bash

# Example
web_users_users:
  - username: gothick
    shell: /bin/zsh
  - username: omm

# Example
web_users_authorised_keys:
  - username: gothick
    key: "{{ some_key_here }}"
  - username: gothick
    key: "{{ some_key_here_for_same_user }}"
  - username: onthescales
    key: "{{ different_user_different_key }}"
