---
# geerlingguy.apache will create a big-ass vhosts file if you
# let it; this lets us manually create our own individual vhosts
# files to keep things simpler and more flexible.
apache_create_vhosts: false

# We'll add our own default vhost if necessary
apache_remove_default_vhost: true

# Should be everything we need to plug PHP in later, etc.
apache_mods_enabled:
  - rewrite
  - ssl
  - headers
  - proxy
  - proxy_fcgi
  - alias
  # For webdav:
  - dav
  - dav_fs
  - dav_lock
  - auth_digest
  # For Docker forwarding
  - proxy_balancer
  - proxy_http
  - slotmem_shm

  # You haven't bothered with pagespeed this time. More trouble than it's worth.

# apache_mods_disabled: []
