---
# These will work from any platform; they just use S3 for storage, so we
# install them whether we're in EC2 or not.
- name: Install S3 backup scripts.
  hosts: all
  become: true

  vars_files:
    # - vault.yml
    - vars.yml

  tasks:
    - name: Install percona-toolkit, used to dump mysql users and privileges separately
      ansible.builtin.apt:
        name: percona-toolkit
        update_cache: true
        cache_valid_time: 3600

    - name: Install S3 backup script
      ansible.builtin.template:
        src: s3_backup.sh.j2
        dest: /usr/local/bin/s3_backup.sh
        owner: root
        group: root
        mode: '0744'

    - name: Add job for s3 backups
      ansible.builtin.cron:
        name: s3 backups
        minute: "0"
        hour: "3"
        weekday: "0"
        user: root
        job: "/usr/local/bin/s3_backup.sh > /dev/null"
        cron_file: s3_backups

    - name: Send s3 backup emails to the right place
      community.general.cronvar:
        name: MAILTO
        value: "{{ admin_email | default('gothick@gothick.org.uk') }}"
        user: root
        cron_file: s3_backups
