---
- name: Install EC2-appropriate snapshot scripts
  hosts: all
  become: true

  vars_files:
    # - vault.yml
    # - vars.yml

  tasks:
    # Because snapshotting EC2 volumes makes no sense if we're not in EC2
    - name: Bail if we're not in EC2
      ansible.builtin.meta: end_host
      when: ansible_facts.ohai_cloud.provider | default(omit) != "ec2"

    - name: Get www EBS volume info
      amazon.aws.ec2_vol_info:
        filters:
          "tag:Name": "www-{{ inventory_hostname }}"
      register: www_vol_info

    - name: Get db EBS volume info
      amazon.aws.ec2_vol_info:
        filters:
          "tag:Name": "db-{{ inventory_hostname }}"
      register: db_vol_info

    - name: Set volume names up
      ansible.builtin.set_fact:
        www_volume_id: "{{ www_vol_info.volumes[0].id }}"
        db_volume_id: "{{ db_vol_info.volumes[0].id }}"

    - name: Install EBS volume snapshotting script
      ansible.builtin.template:
        src: snapshot_ebs_volumes.sh.j2
        dest: /usr/local/bin/snapshot_ebs_volumes.sh
        owner: root
        group: root
        mode: "0744"

    - name: Send cron snapshot emails to the right place
      community.general.cronvar:
        name: MAILTO
        value: "{{ admin_email | default('gothick@gothick.org.uk') }}"
        user: root
        cron_file: daily_snapshot
