plugin: amazon.aws.aws_ec2

# Yee haw
regions:
  - us-east-1

hostnames:
  # Matches the dynamic inventory from provisioners/ec2.yml, so we don't think
  # that there are multiple copies of the same host floating around.
  - tag:Name

# Only count our dev and prod environments; we may have other EC2
# boxes lying around that we don't want to fiddle with.
filters:
  tag:env:
    - prod

# Create a dynamic group for each of our environments
keyed_groups:
  - key: tags.env
    separator: ''

# groups:
#   dev: "'dev' in tags.env"
#   live: "'prod' in tags.env"

# We use the public ipv4 IP address to connect via ssh; this is the
# Elastic IP if the host has one.
compose:
  ansible_host: public_ip_address
