---
- name: Create Ansible user for Vagrant
  hosts: all
  become: true

  tasks:

    - name: Add Ansible user
      ansible.builtin.user:
        name: "ansible"
        state: present
        shell: /bin/bash
        groups: sudo
        append: true

    - name: Add sudoers entry for Ansible user
      ansible.builtin.include_role:
        name: arillso.sudoers
      vars:
        sudoers_sudoers_d_files:
          - name: ansible
            entry: |
              ansible ALL=(ALL) NOPASSWD: ALL

    - name: Add authorised keys
      ansible.posix.authorized_key:
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDl3K/tzUEdvB80r2Gppp7ojFcryQaIA6sXNtb+Nv6WH"
        user: "ansible"
        state: present
