---
- name: Install and configure Docker
  hosts: all
  become: true

  # vars_files:
  #  - vars.yml

  # pre_tasks:

  roles:
    - geerlingguy.docker

    - name: Install required Apache modules for forwarding to Docker
      community.general.apache2_module:
        state: present
        name: proxy
      notify: Reload apache
