---
- name: Install Supervisor
  hosts: all
  become: true

  # vars_files:
  #   - vars.yml

  # roles:

  # pre_tasks:

  tasks:
    - name: Install Supervisor
      ansible.builtin.apt:
        name: supervisor
        state: present
        cache_valid_time: 600

  # We don't configure anything. Apps that use Supervisor will have to do that themselves.
