---
# This Playbook is basically this article: https://ubuntu.com/server/docs/how-to-install-and-use-openvpn
# but in Ansible format.
- name: Install and configure OpenVPN
  hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Install OpenVPN and easy-rsa
      ansible.builtin.apt:
        name:
          - openvpn
          - easy-rsa
        state: present
        cache_valid_time: 3600

  tasks:

    # - name: Create easy-rsa directory
    #   ansible.builtin.file:
    #     path: /etc/openvpn/easy-rsa
    #     state: directory
    #     owner: root
    #     group: root
    #     mode: '0700'

    # - name: Find all easy-rsa content
    #   ansible.builtin.find:
    #     paths: /usr/share/easy-rsa
    #     file_type: any
    #   register: easy_rsa_content

    # - name: Symlink easy-rsa files to /etc/openvpn/easy-rsa
    #   ansible.builtin.file:
    #     src: "{{ item.path }}"
    #     dest: "/etc/openvpn/easy-rsa/{{ item.path | basename }}"
    #     state: link
    #   with_items: "{{ easy_rsa_content.files }}"

    # - name: Copy easy-rsa vars file
    #   ansible.builtin.copy:
    #     src: easy_rsa_vars
    #     dest: /etc/openvpn/easy-rsa/vars
    #     owner: root
    #     group: root
    #     mode: '0600'

    - name: Create easy-rsa directory using make-cadir
      ansible.builtin.command:
        cmd: make-cadir /etc/openvpn/easy-rsa
        creates: /etc/openvpn/easy-rsa

    - name: Template out vars directory
      ansible.builtin.template:
        src: easy_rsa_vars.j2
        dest: "{{ easy_rsa_vars_path }}"
        owner: root
        group: root
        mode: '0600'

    - name: Initialise public key infrastructure
      ansible.builtin.command:
        cmd: ./easyrsa init-pki
        chdir: "{{ easy_rsa_path }}"
        creates: "{{ easy_rsa_pki_path }}"
      environment:
        EASYRSA_VARS_FILE: "{{ easy_rsa_vars_path }}"
        EASYRSA_BATCH: "1"
        # EASYRSA_REQ_CN: "{{ easy_rsa_req_cn }}"
        # EASYRSA_ALGO: "{{ easy_rsa_algo }}"
        # EASYRSA_DIGEST: "{{ easy_rsa

    - name: Build certificate authority
      ansible.builtin.command:
        cmd: ./easyrsa build-ca nopass
        chdir: "{{ easy_rsa_path }}"
        creates: "{{ easy_rsa_pki_path }}/ca.crt"
      environment:
        EASYRSA_VARS_FILE: "{{ easy_rsa_vars_path }}"
        EASYRSA_BATCH: "1"

    - name: Generate server keypair
      ansible.builtin.command:
        cmd: "./easyrsa gen-req {{ ansible_hostname }} nopass"
        chdir: "{{ easy_rsa_path }}"
        creates: "{{ easy_rsa_pki_path }}/private/{{ ansible_hostname }}.key"
      environment:
        EASYRSA_VARS_FILE: "{{ easy_rsa_vars_path }}"
        EASYRSA_BATCH: "1"

    - name: Generate Diffie Hellman parameters
      ansible.builtin.command:
        cmd: "./easyrsa gen-dh"
        chdir: "{{ easy_rsa_path }}"
        creates: "{{ easy_rsa_pki_path }}/dh.pem"
      environment:
        EASYRSA_VARS_FILE: "{{ easy_rsa_vars_path }}"
        EASYRSA_BATCH: "1"

    - name: Create server certificate
      ansible.builtin.command:
        cmd: "./easyrsa sign-req server {{ ansible_hostname }}"
        chdir: "{{ easy_rsa_path }}"
        creates: "{{ easy_rsa_pki_path }}/issued/{{ ansible_hostname }}.crt"
      environment:
        EASYRSA_VARS_FILE: "{{ easy_rsa_vars_path }}"
        EASYRSA_BATCH: "1"

    - name: Copy keys and certificates to /etc/openvpn
      ansible.builtin.copy:
        src: "{{ item }}"
        remote_src: true
        dest: /etc/openvpn/
        owner: root
        group: root
        mode: '0600'
      with_items:
        - "{{ easy_rsa_pki_path }}/dh.pem"
        - "{{ easy_rsa_pki_path }}/ca.crt"
        - "{{ easy_rsa_pki_path }}/issued/{{ ansible_hostname }}.crt"
        - "{{ easy_rsa_pki_path }}/private/{{ ansible_hostname }}.key"
      notify: Restart openvpn

    - name: Create client config directory
      ansible.builtin.file:
        name: "{{ client_config_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copy keys and certificates also to client config dir, as we'll need them there too.
      ansible.builtin.copy:
        src: "{{ item }}"
        remote_src: true
        dest: "{{ client_config_dir }}"
        owner: root
        group: root
        mode: '0600'
      with_items:
        - "{{ easy_rsa_pki_path }}/dh.pem"
        - "{{ easy_rsa_pki_path }}/ca.crt"
        - "{{ easy_rsa_pki_path }}/issued/{{ ansible_hostname }}.crt"
        - "{{ easy_rsa_pki_path }}/private/{{ ansible_hostname }}.key"

    # Generate client certificates.
    # TODO: You'll need to grab pki/ca.crt and pki/issued/homemac.crt
    # to your local machine and configure them in your OpenVPN client.
    # Maybe make this a bit easier by putting them in a tarball
    # somewhere handy?
    - name: Generate client requests
      ansible.builtin.command:
        cmd: "./easyrsa gen-req {{ vpn_client_name }} nopass"
        chdir: "{{ easy_rsa_path }}"
        creates: "{{ easy_rsa_pki_path }}/reqs/{{ vpn_client_name }}.req"
      environment:
        EASYRSA_VARS_FILE: "{{ easy_rsa_vars_path }}"
        EASYRSA_BATCH: "1"
      loop: "{{ client_names }}"
      loop_control:
        loop_var: vpn_client_name

    - name: Generate client certificates
      ansible.builtin.command:
        cmd: "./easyrsa sign-req client {{ vpn_client_name }}"
        chdir: "{{ easy_rsa_path }}"
        creates: "{{ easy_rsa_pki_path }}/issued/{{ vpn_client_name }}.crt"
      environment:
        EASYRSA_VARS_FILE: "{{ easy_rsa_vars_path }}"
        EASYRSA_BATCH: "1"
      loop: "{{ client_names }}"
      loop_control:
        loop_var: vpn_client_name

    - name: Copy client certificates to client config directory
      ansible.builtin.copy:
        src: "{{ easy_rsa_pki_path }}/issued/{{ vpn_client_name }}.crt"
        dest: "{{ client_config_dir }}/{{ vpn_client_name }}.crt"
        remote_src: true
        owner: root
        group: root
        mode: '0600'
      loop: "{{ client_names }}"
      loop_control:
        loop_var: vpn_client_name

    - name: Copy client keys to client config directory
      ansible.builtin.copy:
        src: "{{ easy_rsa_pki_path }}/private/{{ vpn_client_name }}.key"
        dest: "{{ client_config_dir }}/{{ vpn_client_name }}.key"
        remote_src: true
        owner: root
        group: root
        mode: '0600'
      loop: "{{ client_names }}"
      loop_control:
        loop_var: vpn_client_name

    - name: Generate tls key
      ansible.builtin.command:
        cmd: openvpn --genkey --secret /etc/openvpn/ta.key
        creates: /etc/openvpn/ta.key
      notify: Restart openvpn

    - name: Copy tls key to client config directory
      ansible.builtin.copy:
        remote_src: true
        src: /etc/openvpn/ta.key
        dest: "{{ client_config_dir }}/ta.key"
        owner: root
        group: root
        mode: '0600'

    - name: Create server.up.d directory
      ansible.builtin.file:
        path: /etc/openvpn/server.up.d
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Template out server configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode | default('0600') }}"
      with_items:
        - src: server.conf.j2
          dest: /etc/openvpn/server.conf
          mode: '0600'
        - src: server.up.sh.j2
          dest: /etc/openvpn/server.up.sh
          mode: '0700'
        - src: server.down.sh.j2
          dest: /etc/openvpn/server.down.sh
          mode: '0700'
        - src: iptables.up.sh.j2
          dest: /etc/openvpn/server.up.d/iptables.up.sh
          mode: '0700'
        - src: forwarding.up.sh.j2
          dest: /etc/openvpn/server.up.d/forwarding.up.sh
          mode: '0700'

      notify: Restart openvpn

    - name: Enable and start openvpn systemd service
      become: true
      ansible.builtin.systemd:
        name: openvpn@server
        state: started
        daemon_reload: true
        enabled: true

    - name: Template out client configuration file
      ansible.builtin.template:
        src: client.conf.j2
        dest: "{{ client_config_dir }}/{{ vpn_client_name }}.conf"
        owner: root
        group: root
        mode: '0600'
      loop: "{{ client_names }}"
      loop_control:
        loop_var: vpn_client_name

    - name: Bundle client files
      community.general.archive:
        path:
          - "{{ client_config_dir }}/{{ vpn_client_name }}.crt"
          - "{{ client_config_dir }}/{{ vpn_client_name }}.key"
          - "{{ client_config_dir }}/{{ vpn_client_name }}.conf"
          - "{{ client_config_dir }}/ca.crt"
          - "{{ client_config_dir }}/ta.key"
        dest: "{{ client_config_dir }}/{{ vpn_client_name }}.tgz"
        owner: root
        group: root
        mode: '0600'
      loop: "{{ client_names }}"
      loop_control:
        loop_var: vpn_client_name

  handlers:
    - name: Restart openvpn
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: openvpn@server

  post_tasks:
