---
easy_rsa_algo: "ec"
easy_rsa_digest: "sha512"
easy_rsa_dn: "cn_only"
easy_rsa_req_cn: "gothick.org.uk"
easy_rsa_path: /etc/openvpn/easy-rsa
easy_rsa_vars_path: "{{ easy_rsa_path }}/vars"
easy_rsa_pki_path: "{{ easy_rsa_path }}/pki"

client_names:
  - homemac
#  - anotherone

client_config_dir: /etc/openvpn/client_certs

push_routes:
  # Our configured AWS subnet
  - "172.31.16.0 255.255.240.0"
